name: CD with Node

on:
  push:
    branches: [main, dev]
env:
  S3_BUCKET_NAME: pre-project-bucket-seb40-017
jobs:
  frontend:
    name: CI with Node.js
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: client

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: node.js 14설치
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: npm 설치
        run: npm install

      - name: npm 빌드
        run: npm run build

      # build한 후 프로젝트를 압축합니다.
      - name: Make zip file
        run: zip -r ./build-fe.zip .
        shell: bash

      # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 압축한 프로젝트를 S3로 전송합니다.
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://$S3_BUCKET_NAME/build-fe.zip

        # CodeDeploy에게 배포 명령을 내립니다.
      - name: Code Deploy
        run: >
          aws deploy create-deployment --application-name fitchallenge
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name fitchallenge-group
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=build-fe.zip